### ISSUE TITLE
Investigate whether web scrape makes sense or manual updates

### ISSUE THREAD

**Issue by frhino** [sfbrigade/data-covid19-sfbayarea#2]

**Comment by ldtcooper** [comment]
Since we also have people working on a dashboard for San Francisco, I think it definitely makes sense to have a scraper for the SF data. It would be nice to have a generalized scraper that could go to each county's health site and collect numbers, but there are some barriers to doing that. For one, that's a lot of counties which need customized code to get data from the exact HTML for each county's page. Secondly, there are some quirks with some of the pages, like Alameda's numbers not including Berkeley.
None of those are insurmountable, especially since we have to write a bunch of customizable code anyway, but I would say that it only makes sense to write scrapers for counties we are actively working with. I think that means starting with SF (which we've done) and then expanding to the other Bay Area counties: Alameda, Napa, Santa Clara, Contra Costa, Solano, Marin, San Mateo, and Sonoma.
If we want to expand from there, I'd suggest writing scrapers starting with large urban areas and places with large outbreaks, e.g. Los Angeles, Orange, San Diego, Sacramento, etc.

**Comment by ldtcooper** [comment]
With the data that Jason linked in the Slack channel, I'm not sure that it makes sense to do manual data gathering anymore.
