### ISSUE TITLE
Marin County only shows data up to Feb 11

### ISSUE THREAD

**Issue by frhino** [sfbrigade/data-covid19-sfbayarea#203]
**Describe the bug**
Appears to be a pagination issue where the data exists but we're just not accessing all of it from our data file.

**To Reproduce**
1. Go to https://panda.baybrigades.org/main
2. Click on statistics
3. Scroll down to county selector
4. Choose Marin
5. See data goes to Feb 11 and stops
6. Go to https://coronavirus.marinhhs.org/surveillance
7. Verify data goes to April 25 (as of April 28)

**Expected behavior**

**Screenshots**
![image](https://user-images.githubusercontent.com/7381521/116497763-ba928c00-a86d-11eb-8a71-0d21adcdb962.png)

**Additional context**

**Comment by Mr0grog** [comment]
Per discussion earlier this evening and in Slack, it looks like the problem is that the Marin module is not properly paging through the full set of data. It uses `data.utils.SocrataApi.resource()`, which is somewhat simplistic and just makes a single HTTP request, without trying to determine if it needs to page through more results:

https://github.com/sfbrigade/data-covid19-sfbayarea/blob/40a9779552d21803faef5a31be2ad129d9a13c9f/covid19_sfbayarea/data/utils.py#L51-L52

Instead, it should act like our other, slightly more complex API clients and automatically page through the full result set.

For examples of how we do this elsewhere, see:

ArcGIS: https://github.com/sfbrigade/data-covid19-sfbayarea/blob/40a9779552d21803faef5a31be2ad129d9a13c9f/covid19_sfbayarea/data/arcgis.py#L88-L105

CKAN: https://github.com/sfbrigade/data-covid19-sfbayarea/blob/40a9779552d21803faef5a31be2ad129d9a13c9f/covid19_sfbayarea/data/ckan.py#L47-L70

**Comment by Mr0grog** [comment]
Socrata pagination docs: https://dev.socrata.com/docs/paging.html

**Comment by benghancock** [comment]
It looks like there's a [Python package available](https://github.com/xmunoz/sodapy#get_alldataset_identifier-content_typejson-kwargs) for interacting with the SODA API, called `sodapy`, which has a `get_all()` method to handle the pagination for a given data set. Thoughts on the pros and cons of using that, as opposed to our home-grown wrapper?

**Comment by Mr0grog** [comment]
As a short-term fix, I think it’s good to update out minimal client (less impact on the rest of the codebase needing to change to fit sodapy’s API) like you’re doing in #207, but switching to a more robust and maintained package would probably be a good follow-on!
